Add back pass for server.ThreadedHTTPServer
This pass was removed (possibly by mistake) 9 days ago which causes the server to break due to IndentationError
```python
    class HTTPServerThread(threading.Thread):
        ^
IndentationError: expected an indented block
```